### ISSUE TITLE
AFExecutor (Deobfuscated class name) com.appsflyer.AFExecutor$2$1.run

### ISSUE THREAD

**Issue by moamenelsawy18** [AppsFlyerSDK/appsflyer-segment-android-plugin#21]
gradle line : implementation 'com.appsflyer:segment-android-integration:+'

happened on : android 5, 6  and 7
its appeared on fabric crashes not on the development

the crash trace :

Fatal Exception: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

**Comment by k4dima** [comment]
What is the exception rate? And maybe you found any stack trace?

**Comment by af-fess** [comment]
Closed because of non-activity
