### ISSUE TITLE
Update to 5.4.1 or later

### ISSUE THREAD

**Issue by eclipsegst** [AppsFlyerSDK/appsflyer-segment-android-plugin#32]
@af-fess We want to use the lastest AppsFlyerSDK, I was wondering can we put some effort to upgrade it or do we have any plan?

**Comment by af-margot** [comment]
Hi @eclipsegst,
Sorry for the late reply and thank you for your patience! 
We will release a new version with the latest version of AppsFlyer SDK soon, probably during next week.

**Comment by af-margot** [comment]
Hi @eclipsegst ,

We have release [v5.4.4 ](https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin/releases/tag/5.4.4)which uses AppsFlyer SDK 5.4.4.
Closing the issue, thank you!
