### ISSUE TITLE
Overriding allowBackup flag

### ISSUE THREAD

**Issue by akshaymanathkar** [AppsFlyerSDK/appsflyer-segment-android-plugin#33]
# Report

## Plugin Version

ℹ `1.17`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
e.g. ios and android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be tracked

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. No uninstalls on my dashboard

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
I am overriding `allowBackup` attribute in my Main manifest file and setting it to `false`. Will there be any issues with my appsflyer-segment plugin?

**Comment by af-vs** [comment]
@akshaymanathkar Hey!

No, disabling autoBackup will not harm AppsFlyer SDK and shouldn't affect Segment. Although, I cannot be quite sure for Segment, guess you better check with them if you have any concerns.
