### ISSUE TITLE
Appsflyer/Segment Android Plugin still calls deprecated methods

### ISSUE THREAD

**Issue by michaelyatco** [AppsFlyerSDK/appsflyer-segment-android-plugin#35]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
`4.1.1`

## On what Platform are you having the issue?
Android

ℹ Please replace these two lines with the SDK version:
`6.1.0` and `6.0.0`

## What did you do?

ℹ Please replace these two lines with what you did.  
Updated these modules:
    `implementation 'com.appsflyer:segment-android-integration:5.4.4'` (from 5.2.1)
    `implementation 'com.appsflyer:af-android-sdk:6.1.0'` (from 5.4.5)

## What did you expect to happen?
For my app to build and launch with no issue

ℹ Please replace these two lines with what you expected to happen.  
For my app to build and launch with no issue

## What happened instead?
App is built but crashes upon launch

ℹ Please replace these two lines with of what happened instead.  
App is built but crashes upon launch

## Please provide any other relevant information.
Logcat when I try to launch the app:
2020-11-23 09:51:29.803 7349-7349/com.trydriver.driver E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trydriver.driver, PID: 7349
    java.lang.NoSuchMethodError: No virtual method startTracking(Landroid/content/Context;)V in class Lcom/appsflyer/AppsFlyerLib; or its super classes (declaration of 'com.appsflyer.AppsFlyerLib' appears in /data/app/~~8ivQXGhTacj3l7QI0fA8sg==/com.trydriver.driver-0Wceqib1YFUqv8knn1JEWA==/base.apk)
        at com.segment.analytics.android.integrations.appsflyer.AppsflyerIntegration$1.create(AppsflyerIntegration.java:80)
        at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1580)
        at com.segment.analytics.Analytics$2$1.run(Analytics.java:313)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

ℹ Please replace these two lines with more information.

When we updated the modules updates, it appears that Appsflyer is still calling deprecated methods. 

This line, within my Application class, calls Appsflyer files that still have the deprecated methods: 
` .use(AppsflyerIntegration.FACTORY)` 

In the following two cases, we are using `com.appsflyer:af-android-sdk:6.1.0`

* If I "Go To Declaration" for `AppsflyerIntegration.FACTORY` within my Application class and I have `'com.appsflyer:segment-android-integration:5.2.1'` within the gradle.build file, it goes to `AppsflyerIntegration.java`. 

* If I "Go To Declaration" for `AppsflyerIntegration.FACTORY` within my Application class and I have `'com.appsflyer:segment-android-integration:5.4.4'` within the gradle.build file, it goes to `AppsflyerIntegration.class`.

`AppsflyerIntegration.java` and `Appsflyerintegration.class` both have the deprecated methods (eg. `startTracking()` instead of the new `start()`). 

Note: 
<img width="685" alt="Screen Shot 2020-11-23 at 10 12 23 AM" src="https://user-images.githubusercontent.com/24990461/99978858-73f7ad80-2d74-11eb-80a8-3a7009365179.png">
<img width="683" alt="Screen Shot 2020-11-23 at 10 11 31 AM" src="https://user-images.githubusercontent.com/24990461/99978860-74904400-2d74-11eb-8403-a4855c75cd71.png">

The app still works by keeping the modules at these versions:
    `implementation 'com.appsflyer:segment-android-integration: 5.2.1'`
    `implementation 'com.appsflyer:af-android-sdk:5.4.5'`

Please advice. Thank you!

**Comment by af-margot** [comment]
Hi @michaelyatco, 

Thank you for the input! 
However the latest version of **appsflyer-segment-android-plugin** depends on **com.appsflyer:af-android-sdk:5.4.4** as mentioned in the `README`. The methods used are not deprecated in this version.
We will update our plugin soon. In the meantime, you should be able to use our latest release of appsflyer-segment-android-plugin without an issue, please follow the [guide](https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin#21-adding-the-plugin-to-your-project).

**Comment by epool** [comment]
@michaelyatco I think this was just fixed with `com.appsflyer:segment-android-integration:6.1.1` if I'm not wrong.

**Comment by af-margot** [comment]
Hi @epool @michaelyatco ,

Yes, `com.appsflyer:segment-android-integration:6.1.1` supports `com.appsflyer:af-android-sdk:6.1.1`
I will close the issue then!
