### ISSUE TITLE
the latest integration sdk is not published to maven (6.2.0)

### ISSUE THREAD

**Issue by MoemenMostafa** [AppsFlyerSDK/appsflyer-segment-android-plugin#39]
# Report

## Plugin Version

6.2.0

## On what Platform are you having the issue?

6.2.0

## What did you do?

trying to install the latest integration SDK

## What did you expect to happen?

getting the latest version 6.2.0

## What happened instead?

I got an error that the version is not available in maven

**Comment by af-margot** [comment]
Hi @MoemenMostafa ,
We just released it to maven. It should be available soon!
