### ISSUE TITLE
Is there Xamarin binding for this

### ISSUE THREAD

**Issue by pmahend1** [AppsFlyerSDK/appsflyer-segment-android-plugin#40]
# Report

## Plugin Version
Any
ℹ Please replace these two lines with the plugin version.
e.g. via `4.1.1`
NA

## On what Platform are you having the issue?
Android through Xamarin forms

## What did you do?
Switching to segment

We have been using Appsflyer Xamarin nuget. So now we are switching to Segment.
We noticed there is no Xamarin counterpart for that. 
So what should be the way to go ?

Can we use Segment library along with Appsflyer. 

Are there plans to have Xamarin library for this repo?

If not how can we route installation/attribution events through Segment.

I notice we have `AppsFlyerLib.Instance.Start` in the Appsflyer Xamarin library , do we need to have `AppsFlyerConversionDelegate` instead of that for this approach.

**Comment by af-margot** [comment]
Hi @pmahend1,
Thank you for your message! 
Currently, there is no plan to have a Xamarin library for this repo. 
However, using Segment library along with AppsFlyer in Xamarin should not be a problem.
I'm not sure what you mean with the last question, but the `start` method and `ConversionDelegate` are not the same. 
Please contact [support](support@appsflyer.com) if you have more questions on how to implement it!

**Comment by pmahend1** [comment]
So my question is about the approach . I am looking the code you have in this repo..

Call `AppsFlyerLib.Instance.Init(appsFlyerkey, new AppsFlyerConversionDelegate(this), this.Application);`

```
public class AppsFlyerConversionDelegate : Java.Lang.Object, IAppsFlyerConversionListener
    {
        AppCompatActivity activity;

        public AppsFlyerConversionDelegate()
        {
        }

        public AppsFlyerConversionDelegate(MainActivity activity)
        {
        }

        public void OnAppOpenAttribution(IDictionary<string, string> p0)
        {
        }

        public void OnAttributionFailure(string p0)
        {
        }

        public void OnConversionDataFail(string p0)
        {
        }

        public void OnConversionDataSuccess(IDictionary<string, Java.Lang.Object> attributionData)
        {
            Dictionary<string, object> valueMap = new Dictionary<string, object>();
            valueMap.Add("ad_group", attributionData["adgroup"]);
            valueMap.Add("name", attributionData["campaign"]);
            valueMap.Add("source", attributionData["media_source"]);
            Dictionary<string, object> properties = new Dictionary<string, object>();
            properties.Add("provider", "AppsFlyer");
            foreach (var item in attributionData)
            {
                properties.Add(item.Key, item.Value);
            }
            
            properties.Remove("media_source");
            properties.Remove("adgroup");
            properties.Add("campaign", valueMap);
            Segment.Analytics.Client.Track("Install Attributed", properties);//
        }
    }
```

Will this be equivalent code we need to have in C# to accomplish this.

**Comment by pmahend1** [comment]
Thanks @af-margot I have emailed to the support email you mentioned.
