### ISSUE TITLE
Method trackAttributionInformation is deprecated

### ISSUE THREAD

**Issue by dizyaa** [AppsFlyerSDK/appsflyer-segment-android-plugin#55]
# Report

## Plugin Version
Gradle plugin segment-android-integration -> 6.4.3
Gradle plugin installreferrer -> 2.2

## On what Platform are you having the issue?
Android

## What did you do?
Use trackAttributionInformation method for Segment builder

## What did you expect to happen?
This method is **not deprecated**

## What happened instead?
This method is **deprecated**

**Comment by DizelBadCoder** [comment]
JavaDoc comment
```
Automatically track attribution information from enabled providers. This build option has
been removed. TODO (major version change)
```

**Comment by RyanNewsom** [comment]
So what gives?

**Comment by RyanNewsom** [comment]
@af-margot @af-fess @af-obodovskyi @af-vs @af-builder @af

**Comment by morisgateno-appsflyer** [comment]
HI @RyanNewsom 
Thanks for reaching out. Sorry for the delay.
You are right, it is out of the README and example project.
Thanks you.
Moris Gateno.
