### ISSUE TITLE
Cordova Android deeplink on app close does not work when segment integration plugin is used

### ISSUE THREAD

**Issue by zahmed001** [AppsFlyerSDK/appsflyer-segment-android-plugin#59]
# Report

## Plugin Version 

ℹ 6.5.2

## On what Platform are you having the issue?

ℹ Android

## What did you do?

ℹ used the Integration factory in segment initialisation in Applicaiton.java

## What did you expect to happen?

ℹ deeplinking to work with Cordova plugin appsflyer when app is closed.

## What happened instead?

ℹ deeplink works when app is in background but not when closed.

## Please provide any other relevant information.

ℹ using the "https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin" in Ionic application does not work with this plugin.

**Comment by pazlavi** [comment]
👋 Hi @zahmed001 and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
