### ISSUE TITLE
Usage of `androidx.test.ext:junit` in the SDK

### ISSUE THREAD

**Issue by scana** [AppsFlyerSDK/appsflyer-segment-android-plugin#87]
Hi! 

What is the reason for incorporating `androidx.test.ext:junit` in the SDK this way?

Currently it's leaking `junit` as a runtime dependency for consumer apps:
https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin/blob/24c54c0f583314e98792c6ad1ad6edcffc5433c0/app/build.gradle#L41

Perhaps it's a mistake and should be a `testImplementation`?

**Comment by morisgateno-appsflyer** [comment]
Hi @scana.

Thanks for reaching out.
Looks like you are right.
We will fix it in the next release.

Thanks.
Moris
