### ISSUE TITLE
Update SDK Integration to 6.12.2 or above

### ISSUE THREAD

**Issue by jamesclement** [AppsFlyerSDK/appsflyer-segment-android-plugin#90]
# Report

Currently experiencing the following fatal in production for a significant number of users: 
https://github.com/AppsFlyerSDK/appsflyer-android-app/issues/20

A fix is now available in the main SDK 6.12.2, is there a timeline for available updating the segment integration to this version?

## Plugin Version

6.10.3

## On what Platform are you having the issue?

Android

**Comment by morisgateno-appsflyer** [comment]
Hi @jamesclement ,
It's out there.
Have a nice day,
Moris.
